# Generated by Django 4.0.3 on 2022-03-19 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=250)),
                ('landlord', models.CharField(max_length=100)),
                ('total_units', models.CharField(max_length=13)),
                ('occupied_units', models.CharField(max_length=13)),
                ('unoccupied_units', models.CharField(max_length=13)),
            ],
        ),
    ]
