# Generated by Django 4.0.3 on 2022-04-15 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-title'], 'verbose_name': 'Property', 'verbose_name_plural': 'Properties'},
        ),
    ]
