# Generated by Django 4.0.3 on 2022-03-19 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='properties',
            table='temp_user',
        ),
    ]
