# Generated by Django 4.0.3 on 2022-03-19 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_properties_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Properties',
            new_name='Property',
        ),
    ]
