# Generated by Django 4.0.3 on 2022-03-21 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_rename_properties_property'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Property',
        ),
    ]
